project:
  type: website
  output-dir: docs

website:
  title: "Psychology Technicians – Wrexham University"
  navbar:
    logo: images/wrexham-icon.jpeg
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: About/index.qmd
      - text: "Equipment"
        href: Equipment/index.qmd
      - text: "Students"
        menu:
          - text: "Home"
            href: Students/index.qmd
          - text: "Case Studies"
            href: Students/case-studies/index.qmd
          - text: "SONA (In-Development)"
            href: Students/SONA/index.qmd
      - text: "Resources"
        menu:
          - text: "Main Resources Page"
            href: Resources/index.qmd
          - text: "Psychometric Scales"
            href: Resources/index2.qmd
          - text: "Experimental Tasks"
            href: Resources/index3.qmd
      - text: "Recruitment"
        menu:
          - text: "Main Recruitment Page"
            href: Recruitment/index.qmd
          - text: "Available Studies"
            href: Recruitment/index-2.qmd
          - text: "Researcher Requirements"
            href: Recruitment/index-3.qmd
      - text: "OSF"
        menu:
          - text: "GitHub"
            href: "https://wu-psychology-technician.github.io/"
          - text: "Gorilla.sc Open"
            href: "https://app.gorilla.sc/openmaterials/1112705"
          - text: "Research Methods"
            href: RM/index.qmd
      - text: "Contact"
        href: Contact/index.qmd
      - text: "News"
        href: Updates/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    page-footer:
      right: "Last updated: {{< meta date-modified >}}"
    include-after-body: 
      - "_includes/chat-widget.html"

