project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!docs/**"


website:
  title: "Psychology Technicians – Wrexham University"
  favicon: images/wrexham-icon.jpeg

  navbar:
    logo: images/wrexham-icon.jpeg
    background: primary
    left:
      - text: "Home"
        href: index.qmd

      - text: "About"
        href: about/index.qmd

      - text: "Equipment"
        menu: 
          - text: "Main Equipment Page"
            href: equipment/index.qmd
          - text: "Lab Targets - Equipment"
            href: equipment/index-2.qmd

      - text: "Students"
        menu:
          - text: "Main Student Page"
            href: students/index.qmd
          - text: "Case Studies (In Development)"
            href: students/case-studies/index.qmd
          - text: "Risk Assessments"
            href: students/H&s/index.qmd
          - text: "General Ethics Guide"
            href: students/ethics/index.qmd
          - text: "Online Ethics Application Guide"
            href: students/vidatum-academic/index.qmd

      - text: "Resources"
        menu:
          - text: "Main Resources Page"
            href: resources/index.qmd
          - text: "Psychometric Scales"
            href: resources/index2.qmd
          - text: "Experimental Tasks"
            href: resources/index3.qmd
          - text: "Coding Repository"
            href: resources/index4.qmd
          - text: "Immersive Applications"
            href: resources/index5.qmd
          - text: "AI Tools"
            href: resources/index6.qmd

      - text: "Recruitment"
        menu:
          - text: "Main Recruitment Page"
            href: recruitment/index.qmd
          - text: "Available Studies"
            href: recruitment/index-2-soon.qmd
          - text: "Researcher Requirements"
            href: recruitment/index-3.qmd


      - text: "Platforms"
        menu:
          - text: "Main Platforms Page"
            href: platforms/index.qmd
          - text: "Gorilla.sc Open"
            href: https://app.gorilla.sc/openmaterials/1112705
          - text: "SONA (In-development)"
            href: platforms/sona/index.qmd
          - text: "Panopto"
            href: platforms/panopto.qmd
          - text: "JISC"
            href: platforms/jisc.qmd
          - text: "GitHub"
            href: https://github.com/WU-Psychology-Technician
            



      - text: "Data Science"
        menu:
          - text: "Main Data Science page"
            href: data-science/index.qmd
          - text: "Mathematical Prerequisites"
            href: data-science/index5.qmd
          - text: "Probability"
            href: data-science/index-4.qmd
          - text: "Statistics"
            href: data-science/index-2.qmd
          - text: "Research Methods"
            href: data-science/index-3.qmd


      - text: "News"
        menu:
          - text: "Main News Page"
            href: updates/index.qmd
          - text: "Current Technician Tasks"
            href: updates/tasks.qmd
          - text: "FAQ"
            href: updates/FAQ.qmd



      - text: "Contact"
        href: contact/index.qmd


format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true

    page-footer:
      right: "Last updated: {{< meta date-modified >}}"

    include-after-body:
      - "_includes/chat-widget-2.html"
      - "_includes/scroll-to-top.html"
      - "_includes/footer.html"
      - "_includes/technician-chat.html"
      - "_includes/background-lines.html"
