---
title: ""
date-modified: last-modified
date-format: "DD-MM-YYYY"
---

# PsychTech News & Updates

Stay up to date with what the Psychology Technicians activities and learn more about what they do in the background. Moreover, latest announcements, training opportunities, and developments will be shown here and from the Psychology Technicians at Wrexham University.

This page is updated on a regular basis with new information about upcoming workshops, and changes to available resources.

------------------------------------------------------------------------

## Current Status

📢 **No new announcements at the moment**
Check back soon for upcoming events, equipment updates, and student opportunities.

------------------------------------------------------------------------

## What You Can Expect Here

On this page, we’ll share posts regarding:
- **Training sessions & workshops** (e.g., SPSS, Gorilla, Quarto setup)

- **New equipment or software** added to the department news history

- **Guides and resources** that we’ve recently published

- **Opportunities** for students to get involved in projects or events

- **Highlights** from past activities and successful collaborations
