---
title: "Available Studies"
format: html
---

Please direct all specific study related question the principles investigator of the study. You can find their contact information on the informed consent page of the study. If you would like to file a complaint any study, please reach out to the institutional review board listed on the study informed consent. 

If you are a participant at Wrexham University and participating for a Research Module, please direct all existing to the appropriate module leader.


# Home Research - Wrexham University 

All home studies are managed on the **Psychology Technician Moodle webpage**. Please contact at [Psychology Technicianns](mailto:psychology.technician@Wrexham.ac.uk) at Wrexham University to publish your study on that page . Any further questions then please reach out to them if you have any questions at: [psychology.technician@Wrexham.ac.uk](mailto:psychology.technician@wrexham.ac.uk)


# International Research 

These are a list of universities that we have signed a memorandum of understanding to work collaboratively in the process of recruitment. Please visit their websites to access these studies as participants. 


- [Small Liberal Arts College Research Network (SLACR)](https://slacr.weebly.com/available-studies.html)






