---
title: "Available Studies"
format: html
---

Please direct all specific study related question the principles investigator of the study. You can find their contact information on the informed consent page of the study. If you would like to file a complaint any study, please reach out to the institutional review board listed on the study informed consent. 

If you are a participant at Wrexham University and participating for a Research Module, please direct all existing to the appropriate module leader.



# Home Research - Wrexham University 

All home studies are approved and managed on this website the [Psychology Technicianns](mailto:psychology.technician@Wrexham.ac.uk) at the Wrexham University. Please reach out to him if you have any questions at: [psychology.technician@Wrexham.ac.uk](mailto:psychology.technician@wrexham.ac.uk)


## Research 

A list of studies published by our researchers at Wrexham University.

- **Principal Investigator**: Ross Stewart
- **email**: r.stewart01@chester.ac.uk
- **Name of the Study**: Validation of KTANE as an inducer of mild anxiety
- **REC approval**: 5175
- **Study Link**: 





# Module Research

A list of research published only available participaNTS for our psychology students at Wrexham University 

- **Programme Leader**: ?
- **Email**: @wrexham.ac.uk
- **Name of the Study**: ?
- **REC approval**: ?
- **Study Link**: 




# International Research 

These are a list of universities that we have signed a memorandum of understanding to work collaboratively in the process of recruitment. Please visit their websites to access these studies as participants. 


- [Small Liberal Arts College Research Network (SLACR)](https://slacr.weebly.com/available-studies.html)

-





